In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
# 1. Check the version of pandas
pd.__version__

'2.0.3'

In [11]:
df = pd.read_csv('./data/laptops.csv')
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [12]:
# 2. How many records are in the dataset?
df.shape[0]

2160

In [13]:
# 3. How many laptops brands are presented in the dataset?
df['Brand'].nunique()

27

In [26]:
# 4. How many columns in the dataset have missing values?
df[df.columns[df.isnull().any()]].isnull().sum().count()

3

In [29]:
# 5. What's the maximum final price of Dell laptops?
df[df['Brand'] == 'Dell']['Final Price'].max()

3936.0

In [31]:
# 6.1. Find median value of Screen
df['Screen'].median()

15.6

In [37]:
# 6.2. Calculate the most frequent value of Screen
df['Screen'].mode()[0]

15.6

In [38]:
# 6.3. Fill missing values in Screen with the most frequent value
df['Screen'].fillna(df['Screen'].mode()[0], inplace=True)

In [39]:
# 6.4 Calculate the median value of Screen
df['Screen'].median()

15.6

In [40]:
# 7.1. Get all the Innjoo laptops
df[df['Brand'] == 'Innjoo']

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [41]:
# 7.2. Select columns 'RAM', 'Storage', 'Screen'
df[df['Brand'] == 'Innjoo'][['RAM', 'Storage', 'Screen']]

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [49]:
# 7.3. Get underlying NumPy array
X = df[df['Brand'] == 'Innjoo'][['RAM', 'Storage', 'Screen']].values
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [50]:
# 7.4. Compute X'X
XTX = np.dot(X.T, X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [53]:
# 7.5. Compute the inverse of XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [57]:
# 7.6.
y = np.array([1100, 1300, 800, 900, 1000, 1100])
# 7.7 Compute XTX_inv * X.T * y
w = np.dot(np.dot(XTX_inv, X.T), y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [61]:
# 7.8 What's the sum of all elements of w?
w.sum().round(2)

91.3